#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if/end not data.values.create_namespace:
#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata":{"name": "localca-injector"}})
#@overlay/remove
---

#@overlay/match by=overlay.subset({"kind":"Namespace", "metadata": {"name": "localca-injector"}}), expects=[0,1]
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"metadata": {"namespace": "localca-injector"}}), expects=4
---
metadata:
  namespace: #@ data.values.namespace