apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: localca-injector
data:
  setup.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && systemctl restart containerd
